#
# Copyright 2015-2018 Maven Source Dependencies
# Plugin contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - cmd: SET PATH=C:\Users\appveyor\.m2\wrapper\dists\apache-maven-3.5.3-bin\2c22a6s60afpuloj4v181qvild\apache-maven-3.5.3\bin;%JAVA_HOME%\bin;%PATH%
build_script:
  - .\mvnw.cmd clean install -B -Dhttps.protocols=TLSv1.1,TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
on_failure:
  - echo "failed"
  - type srcdeps-maven-quickstarts\target\test-projects\SrcdepsLocalRepositoryManagerTest_mvnGitInterdepModules[3.3.1]_srcdeps-mvn-git-interdep-modules-quickstart\log.txt
cache:
  - C:\Users\appveyor\.m2\wrapper
